name: SRX_QA_Bug_template
description: File a bug report.
labels: ["bug", "triage"]
projects: ["Issue Template"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: Title
  - type: textarea
    id: Summary
    attributes:
      label: Description
      description: Summary of the issue
      placeholder: 
      value:
    validations:
      required: true
  - type: dropdown
    id: EnvironmentDetails
    attributes:
      label: Environment Details
      description: Environment Details
      options:
        - Staging
        - Client staging
        - Pre-prod
        - Production
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Global
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
      default: 0
    validations:
      required: true
  - type: dropdown
    id: Devices
    attributes:
      label: What devices are you seeing the problem on?
      multiple: true
      options:
        - Global
        - Windows
        - Mac
        - Mobile
        - Android
        - Tablet
      default: 0
    validations:
      required: true
   - type: dropdown
    id: BugTypes
    attributes:
      label: Bug Types
      description: Bug Types
      options:
        - Functional
        - ADA Complaince
        - Design
        - Compatibility
        - ETE Forms
      default: 2
    validations:
       required: true
  - type: dropdown
    id: Priority
    attributes:
      label: Priority
      description: Priority
      options:
        - Medium
        - High
        - Low
      default: 0
    validations:
      required: true
  - type: textarea
    id: Steps
    attributes:
      label: Steps to Reproduce
      description: Steps to recreate this issue
      placeholder: Tell us what you see!
      value:
    validations:
       required: true
  - type: input
    id: WorkfrontURL
    attributes:
      label: Workfront URL
      description: Workfront URL
      placeholder: Workfront URL
    validations:
      required: false
  - type: textarea
    id: Comments
    attributes:
      label: Comments
      description: Comments
      render: shell
